#!/bin/bash

clear

json_file="package.json"
Miao_url="https://gitee.com/yoimiya-kokomi/miao-plugin"
TRSS_url="https://gitee.com/TimeRainStarSky/Yunzai-genshin"

current_time=$(date +"%Y-%m-%d %H:%M:%S")
echo "$current_time"

echo -e "\e[1;36m少女祈祷中...\e[0m"

if [ ! -f "$json_file" ]; then
  echo -e "JSON 文件不存在：$json_file\n请在Miao/TRSS-Yunzai根目录执行"
  exit 1
fi

git_clone() {
echo -e "\e[1;35m-\e[0m \e[1;32m开始重置项目\e[0m"

git reset --hard && git pull --rebase --allow-unrelated-histories

    echo -e "\e[1;35m-\e[0m \e[1;32m开始克隆miao-plugin\e[0m"
    git clone --depth=1 $Miao_url.git ./plugins/miao-plugin
    if [ ! -d "./plugins/miao-plugin" ]; then
    echo -e "\e[1;35m-\e[0m \e[1;31m克隆失败，请检查是否为网络问题\e[0m"
    exit 1
fi
}

names=$(grep -oP '"name":\s*"\K[^"]+' "$json_file")

case "$names" in
  "miao-yunzai")
    git_clone
    echo -e "\e[1;35m-\e[0m \e[1;32m克隆完成\e[0m"
    echo -e "\e[1;35m-\e[0m \e[1;32m开始安装依赖\e[0m"
    pnpm install
    echo -e "\e[1;35m-\e[0m \e[1;32m安装完成\e[0m"
    ;;
  "trss-yunzai")
    git_clone
    echo -e "\e[1;35m-\e[0m \e[1;32m克隆完成\e[0m"
    echo -e "\e[1;35m-\e[0m \e[1;32m开始克隆genshin\e[0m"
    git clone --depth=1 $TRSS_url.git ./plugins/genshin && pnpm i
    if [ ! -d "./plugins/genshin" ]; then
    echo -e "\e[1;35m-\e[0m \e[1;31m克隆失败，请检查是否为网络问题\e[0m"
    exit 1
fi
    echo -e "\e[1;35m-\e[0m \e[1;32m克隆完成\e[0m"
    ;;
  "yunzai")
    echo -e "\e[1;31mYunzai-Bot\e[0m"
    echo -e "\e[1;33m建议更换\e[0m \e[1;32mMiao-Yunzai\e[0m"
    sleep 5
    ;;
  *)
    echo -e "\e[1;31m无法判断当前项目\e[0m"
    echo -e "\e[1;33m请自行手动克隆\e[0m"
    exit 1
    ;;
esac
    
exit